input.onButtonPressed(Button.A, function () {
    pins.servoWritePin(AnalogPin.P0, 0)
    basic.pause(1000)
    music.play(music.stringPlayable("C5 B A G F E D C ", 129), music.PlaybackMode.UntilDone)
    basic.showIcon(IconNames.Sad)
    pins.servoWritePin(AnalogPin.P0, 0)
    basic.pause(1000)
    music.play(music.tonePlayable(440, music.beat(BeatFraction.Double)), music.PlaybackMode.InBackground)
    basic.showString("" + (12 * 123))
    music.play(music.tonePlayable(622, music.beat(BeatFraction.Whole)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(349, music.beat(BeatFraction.Double)), music.PlaybackMode.UntilDone)
})
